# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory to /code
WORKDIR /code

# Copy the current directory contents into the container at /code
COPY main.py .

# Specify the command to run your application
CMD ["python3", "/code/main.py"]
